version: "3.8"

services:
  api:
    build: .
    container_name: fastapi_server
    ports:
      - "8000:8000"
    depends_on:
      - redis
    volumes:
      - .:/app

  worker:
    build: .
    container_name: worker
    command: ["python", "worker.py"]
    depends_on:
      - redis
    volumes:
      - .:/app

  redis:
    image: "redis:latest"
    container_name: redis_server
    ports:
      - "6379:6379"
