version: "3.9"

services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile.api
    container_name: fastapi_server
    environment:
      - FAL_API_KEY=${FAL_API_KEY}
    ports:
      - "8000:8000"
    depends_on:
      - redis
    volumes:
      - .:/app
    restart: always
   

  worker:
    build: 
      context: .
      dockerfile: Dockerfile.worker
    container_name: worker
    environment:
      - FAL_API_KEY=${FAL_API_KEY}
    depends_on:
      - redis
    volumes:
      - .:/app
    restart: always

  redis:
    image: "redis:latest"
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
