version: "3"

services:
  redis:
    image: "redis:alpine"
    container_name: "redis_server"
    ports:
      - "6379:6379"

  api:
    build: .
    container_name: "fastapi_app"
    ports:
      - "8000:8000"
    depends_on:
      - redis

  worker:
    build: .
    container_name: "rq_worker"
    command: ["python", "worker.py"]
    depends_on:
      - redis
