version: "3.9"

services:
  api:
    build: .
    context:
    dockerfile: Dockerfile.api
    container_name: fastapi_server
    ports:
      - "8000:8000"
    depends_on:
      - redis
    volumes:
      - .:/app
    restart: always
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

  worker:
    build: 
    context: .
      dockerfile: Dockerfile.worker
    container_name: worker
    command: ["python", "worker.py"]
    depends_on:
      - redis
    volumes:
      - .:/app
    restart: always

  redis:
    image: "redis:latest"
    container_name: redis_server
    ports:
      - "6379:6379"
    restart: always
