name: Text To Image fal-ai/flux-pro/v1.1

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Debug Secrets Name
        run: echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}"

      - name: Debug Secrets Pass
        run: echo "DOCKER_PASSWORD=${{ secrets.DOCKER_PASSWORD }}"


      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Test Docker Login
        run: sudo docker info

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/al-ai-flux-pro-v1.1:tagname .
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/al-ai-flux-pro-v1.1:tagname
